<a href="https://colab.research.google.com/github/prabur90/machinelearning/blob/main/pytorch_tensors_lesson_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [3]:
z=torch.zeros([5,3])
print(z)
print(z.dtype)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
torch.float32


In [5]:
i=torch.ones([5,3], dtype=torch.int16)
print(i)
print(i.dtype)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)
torch.int16


In [14]:
torch.manual_seed(123)
r1=torch.rand(5,3)
print('A random tensor:')
print(r1)

r2=torch.rand(5,3)
print('A Different random tensor:')
print(r2)

torch.manual_seed(123)
r3=torch.rand(5,3)
print('Repeated random tensor:')
print(r3)


A random tensor:
tensor([[0.2961, 0.5166, 0.2517],
        [0.6886, 0.0740, 0.8665],
        [0.1366, 0.1025, 0.1841],
        [0.7264, 0.3153, 0.6871],
        [0.0756, 0.1966, 0.3164]])
A Different random tensor:
tensor([[0.4017, 0.1186, 0.8274],
        [0.3821, 0.6605, 0.8536],
        [0.5932, 0.6367, 0.9826],
        [0.2745, 0.6584, 0.2775],
        [0.8573, 0.8993, 0.0390]])
Repeated random tensor:
tensor([[0.2961, 0.5166, 0.2517],
        [0.6886, 0.0740, 0.8665],
        [0.1366, 0.1025, 0.1841],
        [0.7264, 0.3153, 0.6871],
        [0.0756, 0.1966, 0.3164]])


Arithmetic Operations

In [18]:
ones = torch.ones(2,2, dtype=torch.int32)
print(ones)

twos = torch.ones(2,2)*2
print(twos)

threes = ones + twos
print(threes)

tensor([[1, 1],
        [1, 1]], dtype=torch.int32)
tensor([[2., 2.],
        [2., 2.]])
tensor([[3., 3.],
        [3., 3.]])


Arithmetic Operation with different shape will leads to Runtime Error

In [20]:
r1 = torch.ones(2,2)
r2 = torch.ones(2,3)
print(r1)
print(r2)
r3 = r1+r2

tensor([[1., 1.],
        [1., 1.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


RuntimeError: The size of tensor a (2) must match the size of tensor b (3) at non-singleton dimension 1

In [21]:
r = torch.rand(2, 2) - 0.5 * 2 # values between -1 and 1
print('A random matrix, r:')
print(r)

# Common mathematical operations are supported:
print('\nAbsolute value of r:')
print(torch.abs(r))

# ...as are trigonometric functions:
print('\nInverse sine of r:')
print(torch.asin(r))

# ...and linear algebra operations like determinant and singular value decomposition
print('\nDeterminant of r:')
print(torch.det(r))
print('\nSingular value decomposition of r:')
print(torch.svd(r))

# ...and statistical and aggregate operations:
print('\nAverage and standard deviation of r:')
print(torch.std_mean(r))
print('\nMaximum value of r:')
print(torch.max(r))

A random matrix, r:
tensor([[-0.5983, -0.8814],
        [-0.1726, -0.6179]])

Absolute value of r:
tensor([[0.5983, 0.8814],
        [0.1726, 0.6179]])

Inverse sine of r:
tensor([[-0.6413, -1.0789],
        [-0.1735, -0.6661]])

Determinant of r:
tensor(0.2175)

Singular value decomposition of r:
torch.return_types.svd(
U=tensor([[-0.8624, -0.5063],
        [-0.5063,  0.8624]]),
S=tensor([1.2309, 0.1767]),
V=tensor([[ 0.4901,  0.8717],
        [ 0.8717, -0.4901]]))

Average and standard deviation of r:
(tensor(0.2932), tensor(-0.5676))

Maximum value of r:
tensor(-0.1726)
